### ISSUE TITLE
Pagetype 11 not availible?

### ISSUE THREAD

**Issue by Make66** [in2code-de/luxletter#149]
I could not select page type "Newsletter", so I had no newsletters to send...
After writing a little page TS-Config in the root page, page type was there and usable for newsletter pages:
`TCEFORM.pages.doktype.addItems {
  11 = Luxletter
}`
Funny thing: after this tsconfig, the title of the pagetype was "Newsletter", as it originally should have been...

**Comment by einpraegsam** [comment]
Did you enable multilanguage mode in the global extension settings?
The new doktype is added here: https://github.com/in2code-de/luxletter/blob/develop/ext_tables.php#L96
I just tested again in TYPO3 10 and 11 and the doktype can be used as configured.

**Comment by Make66** [comment]
I have german only. So I choose "Multilanguage mode" to be off. Then the doktype is invisible since the condition in 96:ext_tables is false. Using doktype.addItems brings a new special pagetype=11 and it is useable.
BTW, I don't see why multilanguage feature decides if a doktype is availible or not. (is ok for me).

**Comment by einpraegsam** [comment]
Maybe a short explanation is needed here

We introduced `multilanguagemode` some versions before. That feature basicly does:
- Not require a TYPO3 instance with more then only 1 language but can handle more then 1 if needed
- Pages can be translated and one newsletter per language is created
- Disable to choose an external URL (only internal URLs), instead a select box is rendered what is easier for the editors instead of adding a PID or an complete URL
- Because only internal URL are allowed, a new doktype 11 was introduced

We're not yet sure if we drop the old `not-multilanguage` mode in some future versions, but this would be an option.

For you: If you want to use the old mode and in addition like the doktype 11, the way you did is correct.

I'm going to close this issue for now. Thx for your feedback.
