### ISSUE TITLE
Newsletterconfiguration via Typoscript

### ISSUE THREAD

**Issue by heyse-dc** [in2code-de/luxletter#7]
It would be nice to have the configuration via ts for the newsletter header.
At the moment you can only send one newsletter per installation. Several different newsletters with different channels are apparently not possible at the moment, are they?

**Comment by einpraegsam** [comment]
I could think of a scenario where Newsletter configuration is stored (via Records or as page TSConfig or as TypoScript). Are interested in sponsoring? Otherwise I would keep the ticket open, if someone else also needs this feature.

**Comment by Starkmann** [comment]
We need this feature. And we are right now working on this the feature:
https://github.com/undkonsorten/luxletter/tree/feature/oneConfigurationPerNewsletter

The proposal would be:
# Newsletter configuration

* Choose newsletter configuration before creating a new one
* Newsletter configurations are stored in yml files
* Path to configuration files can be configured via extension configuration
* Overlaying configuration: extension configuration (default)-> yaml configuration

**Comment by Starkmann** [comment]
Typoscript is not a good idea imo, because it requires page context

**Comment by jensengelmann** [comment]
@Starkmann - Do you have any plans on making a PR? I did have a look on your feature branch and it looks really promising.

Since we also want to use luxletter for a multi-site installation, we thought about extending the backend module with a page tree (and therefore storing the newsletters in corresponding sys_folders) in order to implement a database-mount based be user authentification as well as providing an easy way to manage multiple newsletters. Any thoughts on that? (@einpraegsam )

**Comment by Starkmann** [comment]
The pull request is out:
https://github.com/in2code-de/luxletter/pull/31

**Comment by einpraegsam** [comment]
In luxletter there is a senderconfiguration where you can define multiple senders now.
