### ISSUE TITLE
Newsletter can't be saved in bodytext field

### ISSUE THREAD

**Issue by kanow** [in2code-de/luxletter#9]
The saving of a created newsletter is faling. Exception is throwing:

```
1/3) #1470230766 TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException
Data too long for column 'bodytext' at row 1
```
I believe that, my template is just to much code. All the table, tr, td stuff that I need for the newsletter with inlined CSS styles is just to much to save it in a single field. I didn't test yet how much content/code is possible to be saving in the field

Is that saving really necessary? Maybe it's better to generate the newsletter page before sending and cache the site? Like the normal way that TYPO3 did.

**Comment by einpraegsam** [comment]
Hi,

following https://stackoverflow.com/questions/6766781/maximum-length-for-mysql-type-text and https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html then we have to choose type `MEDIUMTEXT` instead of `TEXT` for field tx_luxletter_domain_model_newsletter.bodytext.
Can you please test this for me?

Greetings, Alex

P.S.: At the moment I don't want to rebuild the complete workflow of luxletter and I think the way it is done is basicly a robust way

**Comment by kanow** [comment]
Hi Alex,

`MEDIUMTEXT` is working.

Greetings, Karsten

**Comment by einpraegsam** [comment]
Will be published in the next release
